/****************************************************************************
 *      Copyright (c) 1993, 1994
 *      Century Computing, Inc.
 *      ALL RIGHTS RESERVED
 *
 *      The software (programs, data bases and/or documentation) on or in
 *      any media can not be reproduced, disclosed, or used except under
 *      the terms of the TAE Plus Software License Agreement.
 *
 ***************************************************************************/



#include	"fileinc.inp"	/* file & file position context structs	*/
#include	"terminc.inc"	/* terminal package definitions		*/
#include	"syninc.inc"	/* syntax package structure and defs	*/
#include	"eventinc.inp"	/* e_ package defs & structs		*/
#include	"taskinc.inp"	/* c_ package defs & structs		*/
